### ISSUE TITLE
Bug fix for spurious contours

### ISSUE THREAD

**Issue by StarsoftAnalysis** [benfoxall/contours#2]
The code sometimes creates spurious contours in the shape of a row of 'bowties', such as at the top right of the star in `example.jpg`.  This simple change in `main.js` cures that:

```js
        if(seen[i] || skipping) {
            skipping = true
        } else {
            var contour = traceContour(imageData, i)
            contours.push(contour)
            // this could be a _lot_ more efficient
            contour.forEach(c => {
                seen[c] = true
            })
            skipping = true        // FIX -- add this line
        }
```

The issue is that it needs to be in 'skipping' mode after completing a contour to ensure that it doesn't immediately start a new contour in the middle of the black area.

Since `skipping = true` is now done in both sides of the `if` clause, a bit of refactoring can be done, but I'll leave that as an exercise for the reader.

**Comment by benfoxall** [comment]
Fantastic, thank a lot @StarsoftAnalysis.

I've added your fix and hopefully get some time to come back to the refactoring.
